---

- name: Debug fail2ban_package
  debug:
    var: fail2ban_package

- name: Installing epel packages
  package:
    name: epel-release
    

- name: Installing Fail2ban
  package:
    name: "{{ fail2ban_package }}"
    state: latest
